@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

JobBook *-right-> "1" UniqueApplicationList
JobBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueApplicationList
UniqueTagList -[hidden]down- UniqueApplicationList

UniqueTagList -right-> "*" Tag
UniqueApplicationList -right-> JobApplication

JobApplication -up-> "*" Tag

JobApplication *--> CompanyName
JobApplication *--> Role
JobApplication *--> Deadline
JobApplication *--> Status
@enduml
