@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam arrowThickness 1.2

title Sequence Diagram for DeleteJobCommand Execution

' =======================
' Logic Layer
' =======================
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":JobBookCommandParser" as JobBookCommandParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteJobCommand" as DeleteJobCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

' =======================
' Model Layer
' =======================
box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box


' =======================
' Sequence Flow
' =======================
[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> JobBookCommandParser : parseCommand("delete 1")
activate JobBookCommandParser

create DeleteCommandParser
JobBookCommandParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> JobBookCommandParser
deactivate DeleteCommandParser

JobBookCommandParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteJobCommand
DeleteCommandParser -> DeleteJobCommand
activate DeleteJobCommand

DeleteJobCommand --> DeleteCommandParser : d
deactivate DeleteJobCommand

DeleteCommandParser --> JobBookCommandParser : d
deactivate DeleteCommandParser

JobBookCommandParser --> LogicManager : d
deactivate JobBookCommandParser


' =======================
' Command execution
' =======================
LogicManager -> DeleteJobCommand : execute(Model)
activate DeleteJobCommand

DeleteJobCommand -> Model : getFilteredApplicationList()
activate Model

Model --> DeleteJobCommand : filteredList
deactivate Model

DeleteJobCommand -> Model : deleteJobApplication(jobToDelete)
activate Model

Model --> DeleteJobCommand
deactivate Model

create CommandResult
DeleteJobCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteJobCommand : r
deactivate CommandResult

DeleteJobCommand --> LogicManager : r
deactivate DeleteJobCommand

[<-- LogicManager : r
deactivate LogicManager
@enduml
